---

- name: Cleanup
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
    - name: Truncate files
      command: "truncate -s 0 {{ item }}"
      loop:
        - /etc/machine-id

    - name: Remove folders.
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/cloud
        - /var/log/installer

    - name: Clean Cache
      command: apt autoremove
