---

- name: Setup playbook
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - vars/default.yml

  roles:
    - donhector.workstation.common
    - donhector.workstation.python
    - donhector.workstation.awscli
    - donhector.workstation.bat
    - donhector.workstation.fd
    - donhector.workstation.fzf
    - donhector.workstation.gh
    - donhector.workstation.jq
    - donhector.workstation.ripgrep
    - donhector.workstation.yq
    # - donhector.workstation.asdf
    - { role: geerlingguy.docker, become: yes }

