---
name: 👷 Build

on:
  push:
    branches:
      - main
    path:
      - templates/**
      - ansible/**
      - .github/workflows/build.yml
  workflow_dispatch:

concurrency:
  group: "packer-${{ github.head_ref}}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    strategy:
      matrix:
        template:
          - "ubuntu-2004-live-server"
          - "ubuntu-2204-live-server"
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install qemu
        run: |
          sudo apt update
          sudo apt-get install -y qemu-system-x86

      - name: Cache Packer
        uses: actions/cache@v2
        with:
          path: packer_cache/
          key: cache-${{ hashFiles('packer_cache/*') }}
          restore-keys: |
            cache-

      # Packer comes pre-installed in the runner
      - name: Validate ${{ matrix.template }}
        working-directory: templates/${{ matrix.template }}
        run: |
          packer validate .

      # Github runner does not support accelerator 'kvm', use 'tcg' instead
      - name: Build ${{ matrix.template }}
        working-directory: templates/${{ matrix.template }}
        run: |
          packer build -color=false -on-error=abort -var="accelerator=tcg" .
        env:
          PACKER_LOG: 1

      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.template }}
          path: templates/${{ matrix.template }}/output/
